cxx-gen: Add span() to Error type
dtolnay/cxx pull request #1214
Opened 2023-05-18 15:31 UTC by LeonMatthesKDAB

The Error type exposed in cxx-gen is very minimal currently. For use in CXX-Qt, we'd like to access the span if the Error has one. This would allow us to greatly improve our build script diagnostics (very similar to how CXX displays errors itself).

cc: @ahayzen-kdab
See: https://github.com/KDAB/cxx-qt/issues/536

2023-05-20 09:03 UTC, dtolnay requested changes
In general there are going to be multiple different spans for all the different errors, so an API that only exposes one span is not going to be adequate.

```rust
use quote::quote;

fn main() {
    let tokens = quote! {
        #[cxx::bridge]
        mod ffi {
            enum Enum {}
            unsafe extern "C++" {
                unsafe fn f(ptr: *const &usize);
                fn f(self: &Enum);
            }
        }
    };
    let opt = cxx_gen::Opt::default();
    if let Err(err) = cxx_gen::generate_header_and_cc(tokens, &opt) {
        eprintln!("{:#?}", err);
    }
}
```

```console
Syn(
    Error(
        [
            "C++ does not allow pointer to reference as a type",
            "explicit #[repr(...)] is required for enum without any variants",
            "unsupported receiver type; C++ does not allow member functions on enums",
        ],
    ),
)
```

Could you look into how the cxxbridge-cmd renders multiple errors and figure out what cxx-gen needs to add?

2023-05-22 09:12 UTC, LeonMatthesKDAB commented
Hi, thanks for the review.
Thanks for pointing this out. Wasn't expecting a syn::Error to contain multiple spans.

Will look at cxxbridge-cmd to try and figure out a more adequate API.
I'll let you now when I have something better to suggest.

2023-05-23 16:14 UTC, dtolnay commented
Mimicking syn::Error with an IntoIterator impl seems all right to me. Or `generate_header_and_cc` could just return Vec\<cxx_gen::Error\> as the error type. Feel free to do whatever is easiest for cxx-qt-build, since I do not personally use cxx-gen for anything. Or @adetaylor might have an opinion.

2023-05-25 10:02 UTC, LeonMatthesKDAB commented
@dtolnay I've implemented `IntoIterator` for cxx_gen::Error.
That works out alright for Cxx-Qt (see https://github.com/KDAB/cxx-qt/pull/547) and is compatible with previous uses of the cxx-gen API.

As mentioned in the Commit, I only implemented this on Error and not &Error, as that would require the internal cxx::gen::Error to implement Clone, so to keep the API changes minimal, I left this out.
For Cxx-Qt this means we have to expand the errors directly when creating our diagnostic type, but that's not too bad.

2023-05-26 02:57 UTC, dtolnay approved these changes
Thanks!

2023-05-26 02:57 UTC, merged