Add custom deleter support to UniquePtr
dtolnay/cxx pull request #1305
Opened 2024-01-10 21:31 UTC by darkwisebear

Add the possibility to use shared trivial types as deleters for objects managed by std::unique_ptr / UniquePtr.

2024-05-29 20:07 UTC, darkwisebear commented
@dtolnay Does this PR have chances to be merged as-is or is there still something I need to do with it in order to get it merged?

2024-10-25 14:15 UTC, darkwisebear commented
Well, now this guy has a merge conflict. It shouldn't be a big deal to fix it but is it really worth it? Was it laying around for such a long time because the change is bad? If yes, please tell me.

On a more general side, is it worth that I also add allocator support to vector and shared_ptr? Probably not because I feel that for some reason there is no chance of such changes to ever getting merged. If that is due to lack of time I'd be glad to help here. There's a lot of pending PRs that would be embraced by the community and maybe a lot of stuff that people would be willing to contribute I guess.

2025-08-10 04:27 UTC, dtolnay requested changes
Thanks for the PR!

2025-08-10 04:27 UTC, dtolnay commented on src/unique_ptr.rs
> +}
This is not something I am willing to assume about the internal layout of std::unique_ptr.

Can you suggest some other way to implement this feature?

2025-08-10 05:00 UTC, dtolnay commented
I am pretty confident that this general approach is not a good fit for this library. Depending on exactly how you were planning to use this, I can recommend some alternatives:

1. Use a shared ptr that just always has one reference and is moved like a unique ptr. Shared pointers have a type-erased deleter so the Rust `SharedPtr` binding already works with custom deleters.

1. Use `using UniqueC = std::unique_ptr<C, PmrDeleterForC>` in C++ and write your own Rust `struct UniqueC` and `unsafe impl ExternType for UniqueC`, making whatever layout assumptions you consider appropriate for the set of standard libraries and platforms that your software is targeting.

1. Use `using UniqueC = std::unique_ptr<C, PmrDeleterForC>` and wire up Bindgen to produce the Rust struct for it with the correct layout for the user's platform, adding a manual `ExternType` impl on the Bindgen-generated struct to make it usable in the bridge module by value.

1. Use `using UniqueC = std::unique_ptr<C, PmrDeleterForC>` and then use `UniqueC` as an opaque C++ type in the bridge module, i.e. double boxing.

1. Make your own type-erased unique pointer struct with a well-defined layout. Wrap it in a Rust binding that attaches type information using `PhantomData`.

2025-08-10 05:00 UTC, closed without merging