Fix #532, support opaque Rust types in a rust::Slice
dtolnay/cxx pull request #554
Opened 2020-12-09 22:14 UTC by MichaelRFairhurst

2020-12-10 04:34 UTC, dtolnay requested changes
Thanks, this looks nice.

One thing I am concerned about with this implementation is that the coupling between slice and vec impls will cause poor interaction with #496. For example if we have a hierarchy of two crates where upstream only involves &amp;\[T\] while downstream wants to use Vec\<T\>, and they write:

```rust
// dependency

#[cxx::bridge]
mod ffi {
    extern "Rust" {
        type Thing;

        fn f(slice: &[Thing]);
    }
}
```

```rust
// downstream

#[cxx::bridge]
mod ffi {
    use dependency::Thing;

    extern "Rust" {
        fn g() -> Vec<Thing>;
    }

    impl Vec<Thing> {}
}
```

then they end up with a linker error from duplicating the stride symbol, and "please synthesize a Vec shim *except* the stride symbol" is a confusing thing for the bridge author to need to express.

Decoupling vec and slice such that a functionally identical stride symbol is emitted for each under a different name would fix that, but I wonder if a better fix might be to separate stride from vec/slice altogether and emit a stride accessor unconditionally for every opaque Rust type. Having a size available is going to be generally useful for lots of things on the C++ side as we grow the C++ API of the bindings in cxx.h. It should be fine for C++ to be able to know the size of every type, whether used in vec/slice or not, and whether at compile time (for shared structs, via `sizeof`) or only runtime (for opaque Rust types).

What I'd like to support on the C++ side looks like:

```rust
// include/example.h

#pragma once
#include "rust/cxx.h"

struct Thing;

void f(rust::Slice<Thing> slice);  // forward decl is sufficient i.e. does not
                                   // require knowing the size yet at this point
```

```rust
// src/example.cc

#include "include/example.h"
#include "src/main.rs.h"  // the bridge generated C++ code

void f(rust::Slice<Thing> slice) {
  (void) slice.at(1);  // requires knowing the size of Thing as described below
}
```

where `at` (and similarly `operator[]`, `begin` etc) has a SFINAE to use sizeof(T) if sizeof(T) is not a substitution failure i.e. a definition of T is available and not just a forward decl like for opaque types, otherwise makes a runtime call to find out the size from Rust, otherwise fails to compile if that call is not available.

So for input like this:

```rust
#[cxx::bridge]
mod ffi {
    extern "Rust" {
        type Thing;
    }
}
```

the code generator produces:

```cpp
struct Thing;
namespace detail {
  // every opaque Rust type gets an overload of this:
  inline size_t stride(Thing *) { return cxxbridge1$stride$Thing(); }
}
```

and `at` does something like (untested):

```cpp
namespace detail {
template <typename T, typename = size_t>
struct rust_sizeof {
  size_t operator()() { return stride(static_cast<T *>(nullptr)); }
};
template <typename T>
struct rust_sizeof<T, decltype(sizeof(T))> {  // partial template specialization
  size_t operator()() { return sizeof(T); }
};
} // namespace detail

template <typename T>
T &Slice<T>::operator[](size_t n) noexcept {
  size_t stride = detail::rust_sizeof<T>{}();
  ...
}
```

2020-12-22 08:48 UTC, MichaelRFairhurst commented on include/cxx.h
> +  this->pos += this->stride;
Fixed

2020-12-22 08:48 UTC, MichaelRFairhurst commented on macro/src/expand.rs
> +    }
Good point! With the new approach this is no longer used.

2020-12-22 08:49 UTC, MichaelRFairhurst commented on macro/src/expand.rs
> +            let explicit_impl = types.explicit_impls.get(ty);
Good catch, subtle and important.

With the changes as you suggested, this is fixed.

2020-12-22 09:06 UTC, MichaelRFairhurst commented
New version up for review.

I ran into a few things that make SFINAE become slightly more complicated; nothing super major but we did talk about some over chat, and I ended up feeling like a simple sizeof<T>() template function was the right first approach.

Essentially, the SFINAE approach requires a forward declaration of

```rust
template <typename T, typename = size_t>
struct rust_sizeof; // forward declaration
template <typename T>
struct rust_sizeof<T, decltype(sizeof(T))> {  // partial template specialization
  size_t operator()() { return sizeof(T); }
};
```

because the `stride()` functions we wish to call have not been generated yet. To then be able to call `operator[]` in a `.cpp` file, the `.rs.h` file must define `rust_sizeof` also at least forward declare `Stride(T*)` for all types, independent from declaring their definitions and extern functions. This does not fit with other patterns where generic instantiations are only generated in `.rs.cpp`. These problems are _minor_, I just got a growing impression that the code I was writing did not quite fit the current project as well, and stashed that in a branch before getting the PR to the current state. Happy to revisit this, perhaps after landing this or perhaps before.

One thing I noticed about the PR in this state which may be an issue is that this code:

```
#[cxx::bridge]
mod ffi {
    extern "Rust" {
        type Thing;
    }
}
```

Does not produce a `sizeof` symbol for `Thing`, because it is not a part of `Types.all` (though it is a part of `Types.rust` -- which is a different set type). It will however get a `sizeof` symbol if it is referenced from any APIs (thereby becoming a part of `Types.all`), so I don't think this is a critical path of urgent support or reasonable to rely on in terms of nonlocal types.

2020-12-27 21:21 UTC, dtolnay requested changes

2020-12-27 21:57 UTC, merged

2020-12-27 21:58 UTC, dtolnay reviewed
I merged this with a parallel set of fixes linked below.

Thanks!

#594, #595, #596, #597, #598, #599, #600, #601, #602, #603, #604, #605

2020-12-27 21:58 UTC, dtolnay commented on gen/src/write.rs
> +    writeln!(out, "::std::size_t rust_sizeof<{}>() {{", typename);
I am hesitant about over-reliance on the linker for resolving these template specializations. If the user winds up instantiating `rust::Slice` in C++ with some type that they shouldn't, in this implementation they would only find that out as a link error, not a compile error, due to the template declaration (without definition) `template <typename T> size_t rust_sizeof()` present in include/cxx.h. In general deferring errors from compile time to link time makes them harder to debug.

I found a different way to do this which doesn't use undefined template declarations and is able to surface all errors at compile time: see #595 + #597.

2020-12-27 21:58 UTC, dtolnay commented on include/cxx.h
> +  T &at(std::size_t n);
These changes are not related to opaque type support so I've pulled them out to #598.

2020-12-27 21:58 UTC, dtolnay commented on include/cxx.h
> +  std::size_t stride;
Extracted to #600 + #601.

2020-12-27 21:58 UTC, dtolnay commented on syntax/check.rs
> +        Type::Ident(ident) => !is_opaque_cxx(cx, &ident.rust),
Extracted to #603.

2020-12-27 21:58 UTC, dtolnay commented on src/symbols/rust_vec.rs
> -            }
Extracted to #604.

2020-12-27 21:58 UTC, dtolnay commented on src/symbols/rust_sizeof.rs
> +rust_stride_shims!("string", RustString);
The alternative approach in #597 makes these not needed.

2020-12-27 21:58 UTC, dtolnay commented on include/cxx.h
> +  it.stride = this->stride();
Fixed in #602.

2020-12-28 20:19 UTC, MichaelRFairhurst commented on tests/ffi/lib.rs
> +        fn c_take_slice_not_usized_mut(s: &mut [Second]);
I meant sizeof(T) != sizeof(usize), I can see how that is unclear! :)

2020-12-28 20:20 UTC, MichaelRFairhurst commented on tests/ffi/tests.cc
>    }
Correct -- I could and should have updated this accordingly!

2020-12-28 20:21 UTC, MichaelRFairhurst commented on macro/src/expand.rs
> +            }
I saw you chose instead to emit for "RustType()" in "apis." I was wondering if that was the best approach, good to get feedback that it is! :)

2020-12-28 20:27 UTC, dtolnay commented on tests/ffi/lib.rs
> +        fn c_take_slice_not_usized_mut(s: &mut [Second]);
Well sizeof(T) is actually the same as sizeof(usize) here.

```rust
println!("{}", std::mem::size_of::<Second>());
println!("{}", std::mem::size_of::<usize>());
```

```console
8
8
```

2020-12-28 23:01 UTC, MichaelRFairhurst commented on tests/ffi/lib.rs
> +        fn c_take_slice_not_usized_mut(s: &mut [Second]);
Good point!